let types = ["[Waste type]",
    "Waste oils - Sludge(1100)",
    "Waste oils - Bilge water(1200)",
    "Waste oils - Other - Used engine oil(1301)",
    "Waste oils - Other(1300)",
    "Garbage - Food waste (2100)",
    "Garbage - Plastic(2200)",
    "Garbage - Other - International catering waste(2301)",
    "Garbage - Other - Paper products(2302)",
    "Garbage - Other - Rags(2303)",
    "Garbage - Other - Glass(2304)",
    "Garbage - Other - Metal(2305)",
    "Garbage - Other - Bottles(2306)",
    "Garbage - Other - Crockery(2307)",
    "Garbage - Other - Incinerator ashes and clinkers(2308)",
    "Garbage - Other - Animal carcasses(2309)",
    "Garbage - Other - Special items (e.g. medical waste, oily rags, paint, cans, dated pyrotechnics, batteries, print cartridges,  etc.)(2310)",
    "Garbage - Other - Cooking oil (2311)",
    "Garbage - Other - Deck and external surfaces wash water containing cleaning agents or additives harmful to the marine environment(2312)",
    "Garbage - Other(2300)",
    "Sewage(3000)",
    "Cargo associated waste(4000)",
    "Cargo associated waste - Marpol Annex V - Other(4100)",
    "Cargo associated waste - Marpol Annex V - Dunnage, lining or packing material(4101)",
    "Cargo residues(5000)",
    "Cargo residues - Marpol Annex I - Other(5100)",
    "Cargo residues - Marpol Annex I - Oily tank washings(5101)",
    "Cargo residues - Marpol Annex I - Oily (dirty) ballast water(5102)",
    "Cargo residues - Marpol Annex I - Scale and sludge from tank cleaning(5103)",
    "Cargo residues - Marpol Annex II - Other(5200)",
    "Cargo residues - Marpol Annex II - Washing waters containing noxious cargo residues(5201)",
    "Cargo residues - Marpol Annex II - Ballast water containing noxious cargo residues(5202)",
    "Cargo residues - Marpol Annex V - Cargo hold washing water containing residues and or cleaning agents or additives harmful to the marine environment(5301)",
    "Waste oils - Sludge(1100)",
    "Waste oils - Bilge water(1200)",
    "Waste oils - Other - Used engine oil(1301)",
    "Waste oils - Other(1300)",
    "Garbage - Food waste (2100)",
    "Garbage - Plastic(2200)",
    "Garbage - Other - International catering waste(2301)"]
export default types;